apps/wangguang/urls.py
from django.conf.urls import url, include
# from wangguang import views
from apps.wangguang import views
from rest_framework import routers


route = routers.DefaultRouter()

route.register(r'SysInfo', views.SysInfoViewSet)

# app_name = 'wangguang'
app_name = 'apps.wangguang'
urlpatterns = [
    url(r'^manage$', views.GatewayManageView.as_view(), name='gatewaymanage'),  # 注册页面
    url(r'^info$', views.GatewayInfoView.as_view(), name='gatewayinfo'),  # 注册页面
    url(r'^sysinfo$', views.GatewaySysInfoView.as_view(), name='gatewaysysinfo'),  # 注册页面
    url(r'^service$', views.GatewayServiceView.as_view(), name='gatewayservice'),  # 注册页面
    url(r'^database', views.getlispic, name="database"),
]

edgebox_web/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.user.views import LoginView
from apps.shebei.views import DeviceView
from django.contrib.auth.decorators import login_required

name="main"
urlpatterns = [

    path('apidata/',include('apps.apidata.urls', namespace='apidata')),
    path('admin/', admin.site.urls),
    # path('search/', include('haystack.urls')),  # 全文检索框架
    path('user/', include('apps.user.urls', namespace='user')),  # 用户登录注册模块
    path('wangguang/', include('apps.wangguang.urls', namespace='wangguang')),  # 网关管理模块
    path('m5/', include('apps.m5.urls', namespace='m5')),  # m5扩展模块
    path('shebei/', include('apps.shebei.urls', namespace='shebei')),  # 设备管理模块
    path('yuancheng/', include('apps.yuancheng.urls', namespace='yuancheng')),  # 远程管理模块
    path('loginfo/', include('apps.loginfo.urls', namespace='loginfo')),  # 日志管理模块
    path('qudong/', include('apps.qudong.urls', namespace='qudong')),  # 驱动管理模块
    path('login/', LoginView.as_view(), name="login"),  # 登录页面
    path('accounts/login/', LoginView.as_view(), name="login"),  # 登录页面
    path('', LoginView.as_view()),  # 登录页面
    path('index/', login_required(DeviceView.as_view()), name="index"),  # 主页(登录验证)
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]

apps/wangguang/models.py
from django.db import models
from db.base_model import BaseModel

# Create your models here.


class RegisterInfo(BaseModel):
    '''网关产品注册信息模型类'''
    gateway_name= models.CharField(max_length=30, verbose_name="网关唯一名称")
    gateway_key= models.CharField(max_length=100, verbose_name="网关id")
    gateway_secret= models.CharField(max_length=200, verbose_name="网关秘钥")
    gateway_authurl= models.CharField(max_length=200, verbose_name="网关鉴权URl")
    gateway_subdevice_num= models.IntegerField(default=1, verbose_name="网关子设备数量")
    gateway_model= models.CharField(max_length=30, verbose_name="网关型号")
    gateway_trade_name= models.CharField(max_length=30, verbose_name="网关厂商名称")
    gateway_registration_time= models.DateTimeField(verbose_name="网关注册时间")
    gateway_location= models.CharField(max_length=30, verbose_name="网关位置信息")
    gateway_reset_time= models.DateTimeField(verbose_name="网关最近恢复出厂日期")
    gateway_remark= models.CharField(max_length=50,verbose_name="网关描述")

    class Meta:
        db_table = 'gateway_register_info'
        verbose_name = '网关产品注册信息'
        verbose_name_plural = verbose_name

class SysInfo(BaseModel):
    '''网关系统信息模型类'''
    NET_STATUS_CHOICES = (
        (0, '网络状态正常'),
        (1, '网络状态')
    )
    sys_hostname= models.CharField(max_length=30, verbose_name="系统主机用户名称")
    sys_product_name= models.CharField(max_length=30, verbose_name="产品名称")
    sys_os= models.CharField(max_length=30, verbose_name="系统运行环境")
    sys_ip= models.CharField(max_length=30, verbose_name="系统网络IP地址")
    sys_mac= models.CharField(max_length=30, verbose_name="系统网络MAC地址")
    sys_mask= models.CharField(max_length=30, verbose_name="系统网络子网掩码")
    sys_gateway= models.CharField(max_length=30, verbose_name="系统网络默认网关")
    sys_net_status= models.SmallIntegerField(default=0, choices=NET_STATUS_CHOICES, verbose_name="系统网络状态")
    sys_rateof_cpu= models.CharField(max_length=30, verbose_name="系统CPU使用率")
    sys_memory= models.CharField(max_length=30, verbose_name="系统当前剩余内存")
    sys_memory_size= models.CharField(max_length=30, verbose_name="系统内存大小")
    sys_harddisk= models.CharField(max_length=30, verbose_name="系统当前剩余硬盘大小")
    sys_harddisk_size= models.CharField(max_length=30, verbose_name="系统硬盘大小")
    sys_usb_num= models.IntegerField(default=4, verbose_name="系统USB接口数量")
    sys_rs232_num= models.IntegerField(default=2, verbose_name="系统rs232接口数量")
    sys_use_usb_num= models.IntegerField(null=True,default=4, verbose_name="系统USB使用數量")
    sys_com = models.CharField(null=True,max_length=30, verbose_name="當前COM口")
    sys_running_time= models.CharField(default="0秒", max_length=30, verbose_name="系统运行时间")
    sys_local_time= models.DateTimeField(verbose_name="系统本地时间")
    sys_out_time= models.DateTimeField(verbose_name="系统出厂时间")
    sys_net_model= models.CharField(max_length=30, verbose_name="系统网络模块")

    def __unicode__(self):
        return '%d: %s' % (self.pk, self.sys_product_name)

    class Meta:
        db_table = 'gateway_sys_info'
        verbose_name = '网关系统信息'
        verbose_name_plural = verbose_name

apps/wangguang/views.py
from django.shortcuts import render
from django.views.generic import View
# from wangguang.models import RegisterInfo, SysInfo
from apps.wangguang.models import RegisterInfo, SysInfo
import datetime, requests
from rest_framework import viewsets, filters, pagination
from .serializers import SysInfoSerializers
from apps.wangguang.utils.systemos import message,main
from rest_framework.decorators import api_view
from django.http import HttpResponse,JsonResponse

# Create your views here.

# app_name = 'apps.wangguang'
# /gateway/manage
class GatewayManageView(View):
    '''网关管理'''
    def get(self, request):

        data = RegisterInfo.objects.all().order_by('-id')[0]
        context = {
            "data": data
        }
        # session = requests.Session()
        # session.trust_env = False
        # data = session.get(url="http://127.0.0.1:9090/apidata/all")
        # print(data.json())
        return render(request, 'wangguang/Gateway_Main.html' , context)

    def post(self, request):
        gateway_name=request.POST.get("gateway_name")
        gateway_id=request.POST.get("gateway_id")
        gateway_secret=request.POST.get("gateway_secret")
        gateway_authurl=request.POST.get("gateway_authurl")
        gateway_location=request.POST.get("gateway_location")
        gateway_remark=request.POST.get("gateway_remark")
        # print(gateway_name,gateway_location,gateway_remark,gateway_id,gateway_secret)
        data=RegisterInfo.objects.all().order_by('-id')[0]
        data.gateway_name=gateway_name
        data.gateway_id=gateway_id
        data.gateway_secret=gateway_secret
        data.gateway_authurl=gateway_authurl
        data.gateway_location=gateway_location
        data.gateway_remark=gateway_remark
        data.save()
        context = {
            "data": data
        }
        return render(request, 'wangguang/Gateway_Main.html', context)

# /gateway/info
class GatewayInfoView(View):
    '''网关基本信息'''
    def get(self, request):
        data=RegisterInfo.objects.all().order_by('-id')[0]
        context={
            "data": data
        }

        return render(request, 'wangguang/Gateway_Information.html', context)

# /gateway/sysinfo
class GatewaySysInfoView(View):
    '''网关系统信息'''
    def get(self, request):
        data = SysInfo.objects.all().order_by('-id')[0]
        context = {
            "data": data
        }

        return render(request, 'wangguang/System_Information.html', context)

# /gateway/service
class GatewayServiceView(View):
    '''网关基本信息'''
    def get(self, request):
        return render(request, 'wangguang/Initiated_Service.html')


class PageSet(pagination.PageNumberPagination):
    # 页面大小
    page_size = 10
    page_size_query_param = "size"
    max_page_size = 10
    page_query_param = "page"

class SysInfoViewSet(viewsets.ModelViewSet):
    # 指定结果集并设置排序
    queryset = SysInfo.objects.all().order_by('-pk')
    serializer_class = SysInfoSerializers
    pagination_class = PageSet
    # 配置搜索功能
    filter_backends = (filters.SearchFilter,)
    # 设置搜索的关键字
    search_fields = ('=sys_hostname', 'sys_product_name')
    # 设置搜索出的结果中需要排序的字段
    ordering_field = ('sys_hostname', 'sys_product_name')




@api_view(['GET', 'POST'])
def getlispic(request, format=None,):
    if request.method == "GET":
        now_time = datetime.datetime.now()
        type = request.GET.get("type")
        # try:
        # if type:
        main(SysInfo)
        # except Exception as e:
        #     print(e)
        db = SysInfo.objects.filter().order_by("id")
        obj = PageSet()
        page_list = obj.paginate_queryset(db, request)
        ser = SysInfoSerializers(instance=page_list, many=True)
        response = obj.get_paginated_response(ser.data)
        end_time = datetime.datetime.now()
        time = end_time - now_time
        print(time)
        return response

        # start_time = request.GET.get("start_time")
        # end_time = request.GET.get("end_time")
        # print(type, start_time, end_time)
        # if not type:
        #
        # else:
        # if type == 1:

        # if not all([start_time, end_time]):
        #     db = Log_list.objects.filter(log_no=type).order_by("id")
        #     obj = PageSet()
        #     page_list = obj.paginate_queryset(db, request)
        #     ser = Log_listSerializers(instance=page_list, many=True)
        #     response = obj.get_paginated_response(ser.data)
        #     return response
        # else:
        #     db = Log_list.objects.filter(log_no=type, create_time__gt=start_time,
        #                                  create_time__lt=end_time).order_by("id")
        #     obj = PageSet()
        #     page_list = obj.paginate_queryset(db, request)
        #     ser = Log_listSerializers(instance=page_list, many=True)
        #     response = obj.get_paginated_response(ser.data)
        #     return response

    if request.method == "POST":
       pass

templates/wangguang/Gateway_Information.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" href="{% static 'css/gateway_manage/Gateway_information.css' %}" />
		<link rel="stylesheet" href="{% static 'css/pop.css' %}" />
		<link rel="stylesheet" href="{% static 'css/information.css' %}" />
	</head>
	<body>
		<div id="edit" class="operation div_cursor" onclick="clickEdit('geteway_popup')">
			<img src="{% static 'img/gateway/gateway_pop/u44.png' %}" />&nbsp;&nbsp;&nbsp;<span>编辑</span>
		</div>
		<div class="table_div">
			<table id="table">
				<tr>
					<td style="width: 255px;">网关名称</td>
						<td class="td-right">{{ data.gateway_name }}</td>
				</tr>
				<tr>
					<td>网关ID</td>
					<td class="td-right">{{ data.gateway_key }}</td>
				</tr>
				<tr>
					<td>子设备数</td>
					<td class="td-right">{{ data.gateway_subdevice_num }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a style="color: rgb(36, 109, 255);cursor: pointer;" onclick="go_sub_list()">前往子设备列表</a></td>
				</tr>
				<tr>
					<td>厂商型号</td>
					<td class="td-right">{{ data.gateway_model }}</td>
				</tr>
				<tr>
					<td>厂商名称</td>
					<td class="td-right">{{ data.gateway_trade_name }}</td>
				</tr>
				<tr>
					<td>注册时间</td>
					<td>{{ data.gateway_registration_time|date:"Y-m-d H:i:s" }}</td>
				</tr>
				<tr>
					<td class="bottom_td">网关描述</td>
					<td class="bottom_td">{{ data.gateway_remark }}</td>
				</tr>
				<tr>
					<td>位置信息</td>
					<td class="td-right">{{ data.gateway_location }}</td>
				</tr>
				<tr>
					<td>最近恢复出厂日期</td>
					<td class="td-right">{{ data.gateway_reset_time|date:"Y-m-d H:i:s" }}</td>
				</tr>
			</table>
		</div>	
		<script type="text/javascript" src="{% static 'js/gateway_manage/Gateway_Information.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/Information.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/jquery1.3.2.js' %}" ></script>
	</body>
</html>

templates/wangguang/Gateway_Main.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" href="{% static 'css/page.css'%}" />
		<link rel="stylesheet" href="{% static 'css/Small_Main.css'%}" />
		<link rel="stylesheet" href="{% static 'css/iframe.css'%}" />
		<link rel="stylesheet" href="{% static 'css/pop.css' %}" />
		<link rel="stylesheet" href="{% static 'css/font.css' %}" />
	</head>

	<body>
		<div class="gateway_top">
			<div class="page_tittle">
				<!--<span>网关管理&nbsp;&nbsp;&nbsp;&gt;&nbsp;&nbsp;&nbsp;网关信息</span>-->
				<span>网关管理&nbsp;&nbsp;&nbsp;>&nbsp;&nbsp;&nbsp;&nbsp;<span id="log_sub_title">网关信息</span></span>
			</div>
		</div>
		<div id="gateway_small" class="smallMenu">
			<a style="text-decoration: none;">
				<div class="menu" onclick="clickDiv(className,0,0);clickM(className,0)" onmouseover="over(className,0);overM(className,0)" onmouseout="out(className,0)">
					<div class="smallMenu_div_word">网关信息&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&gt;</div>
				</div>
			</a>
			<a style="text-decoration: none;">
				<div class="menu" onclick="clickDiv(className,1,0);clickM(className,1)" onmouseover="over(className,1);overM(className,1)" onmouseout="out(className,1)">
					<div class="smallMenu_div_word">系统信息&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&gt;</div>
				</div>
			</a>
			<a style="text-decoration: none;">
				<div class="menu" onclick="clickDiv(className,2,0);clickM(className,2)" onmouseover="over(className,2);overM(className,2)" onmouseout="out(className,2)">
					<div class="smallMenu_div_word">网关服务&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&gt;</div>
				</div>
			</a>
		</div>
		<!--<iframe id="gateway_iframe" class="css_iframe" name="gateway_iframe" src="Gateway_Information.html"></iframe>-->
		<iframe id="gateway_iframe" class="css_iframe" name="gateway_iframe" src="{% url 'wangguang:gatewayinfo' %}"></iframe>

		<div id="podiv">
			<form action="" method="post">
				{% csrf_token %}
				<div id="geteway_popup">
					<div class="pop_top">
						<div class="pop_img"><img src="{% static 'img/gateway/gateway_pop/u44.png' %}" /></div>
						<div class="pop_tittle text_left"><span class="tittle_label">网关信息编辑</span></div>
						<div class="pop_close div_cursor" onclick="pop_close('geteway_popup')"><img src="{% static 'img/gateway/gateway_pop/u423.png' %}" /></div>
					</div>
					<div class="pop_line"><img src="{% static 'img/gateway/u130.png' %}" width="460px" /></div>
					<div class="pop_message">
						<div class="pop_content">
							<div class="pop_label">
								<span><sup class="font_red">*</sup>网关名称：</span>
							</div>
							<div class="pop_gateway_input">
								<input value="{{ data.gateway_name }}" name="gateway_name" type="text" maxlength="9" placeholder="请输入网关名称(a-z,A-Z,0-9)" class="pop_input_gateway" type="text" />
								<!--<input class="pop_input_gateway" type="text" maxlength="9" placeholder="请输入网关名称(a-z,A-Z,0-9)" />-->
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span><sup class="font_red">*</sup>网关ID：</span>
							</div>
							<div class="pop_gateway_input">
								<input value="{{ data.gateway_key }}" name="gateway_id"  placeholder="请输入网关ID(0-9)" class="pop_input_gateway" type="text" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span><sup class="font_red">*</sup>网关Secret：</span>
							</div>
							<div class="pop_gateway_input">
								<input value="{{ data.gateway_secret }}" name="gateway_secret"  placeholder="请输入网关Secret" class="pop_input_gateway" type="text" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span><sup class="font_red">*</sup>网关鉴权URL：</span>
							</div>
							<div class="pop_gateway_input">
								<input value="{{ data.gateway_authurl }}" name="gateway_authurl" placeholder="请网关鉴权URL" class="pop_input_gateway" type="text" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span>位置信息：</span>
							</div>
							<div class="pop_gateway_input">
								<input value="{{ data.gateway_location }}"  name="gateway_location"   placeholder="请输入位置信息"  class="pop_input_gateway" type="text" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span>网关描述：</span>
							</div>
							<div class="pop_gateway_input">
								<input value="{{ data.gateway_remark }}"  placeholder="请输入网关描述"  name="gateway_remark" class="pop_input_gateway">
							</div>
						</div>
					</div>
					<button id="gateway_submit_div" type=submit class="new_submit div_cursor text_center" >保存</button>
					<!--<div class="submit div_cursor" onclick="pop_save('geteway_popup')">-->
						<!--<p>保存</p>-->
					<!--</div>-->
					<button id="gateway_close_div" type=button class="new_close div_cursor text_center" onclick="pop_close('geteway_popup')">取消</button>
					<!--<div class="close div_cursor" onclick="pop_close('geteway_popup')">-->
						<!--<p>取消</p>-->
					<!--</div>-->
					<!--<div id="gateway_submit_div" class="new_submit div_cursor text_center" onclick="pop_save('geteway_popup')">-->
						<!--<p>保存</p>-->
					<!--</div>-->
					<!--<div id="gateway_close_div" class="new_close div_cursor text_center" onclick="pop_close('geteway_popup')">-->
						<!--<p>取消</p>-->
					</div>
			</form>

			<form action="" method="post">
				<div id="gateway_Restart" class="div_position div_shadow div_backgr div_radius">
					<div class="pop_submit_img"><img src="{% static 'img/gateway/gateway_pop/u387.png' %}" /></div>
					<div class="pop_tips"><span class="font_orange">温馨提示</span></div>
					<div class="pop_line"><img src="{% static 'img/gateway/gateway_pop/u363.png' %}" width="300px" /></div>
					
					<div id="submit_pop_tips"><span>确定重启网关的采集程序吗？</span></div>
					<div class="tips_submit new2_submit div_cursor text_center" onclick="pop_save('gateway_Restart')">
						<p>确定<p>
					</div>
					<div class="tips_close new2_close div_cursor text_center" onclick="pop_close('gateway_Restart')">
						<p>取消</p>
					</div>
				</div>
			</form>
			
			<form action="" method="post">
				<div id="gateway_factory" class="div_position div_shadow div_backgr div_radius">
					<div class="pop_submit_img"><img src="{% static 'img/gateway/gateway_pop/u387.png' %}" /></div>
					<div class="pop_tips"><span class="font_orange">温馨提示</span></div>
					<div class="pop_line"><img src="{% static 'img/gateway/gateway_pop/u363.png' %}" width="300px" /></div>
					
					<div id="pop_pass_input">请输入密码：&nbsp;&nbsp;&nbsp;<span><input type="password"/></span></div>
					<div class="tips_submit new2_submit div_cursor text_center" onclick="pop_save('gateway_factory')">
						<p>確定<p>
					</div>
					<div class="tips_close new2_close div_cursor text_center" onclick="pop_close('gateway_factory')">
						<p>取消</p>
					</div>
				</div>
			</form>
		</div>
		<script type="text/javascript" src="{% static 'js/jquery.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/gateway_manage/Gateway_Main.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/page.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/pop.js' %}"></script>
	</body>

</html>

templates/wangguang/Initiated_Service.html
<!DOCTYPE html>
{% load staticfiles%}
<html>
	<head>
		<meta charset="UTF-8">
		<title>网关服务</title>
		<link rel="stylesheet" href="{% static 'css/gateway_manage/Initiated_Server.css' %}" />
	</head>
	<body>
		<div id="ini_tips"><span>重新启动和恢复出厂设置都将使数据采集中断，请谨慎操作！</span></div>
		<div class="submit" onclick="clickRes()"><span>重新启动</span></div>
		<div class="sub_tips"><span>重新启动即为重启程序，程序一旦重启数据采集<br />将会中断，网页将跳转至登录页面，请谨慎操作！</span></div>
		<div class="submit" onclick="clickFac()"><span>恢复出厂设置</span></div>
		<div class="sub_tips"><span>恢复出厂设置将会清除您的所有<br />配置信息，需要您重新配置，请谨慎操作！</span></div>
		<script type="text/javascript" src="{% static 'js/gateway_manage/Initiated_Service.js' %}" ></script>
	</body>
</html>

templates/wangguang/System_Information.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" href="{% static 'css/gateway_manage/System_Information.css' %}" />
	</head>
	<body>
		<fieldset id="system_01" class="system">
	    	<legend><p>系統</p></legend>
	    	<div id="left_div">
		    	<div class="left_info"><div class="info_left_label">主机名：</div><div class="info_right_label">{{ data.sys_hostname }}</div></div>
		    	<div class="left_info"><div class="info_left_label">产品名称：</div><div class="info_right_label">{{ data.sys_product_name }}</div></div>
		    	<div class="left_info"><div class="info_left_label">操作系统：</div><div class="info_right_label">{{ data.sys_os }}</div></div>
		    	<div class="left_info"><div class="info_left_label">网络模块：</div><div class="info_right_label">{{ data.sys_net_model }}</div></div>
	    	</div>
	    	<div id="right_div">
	    		<div class="right_info"><div class="info_left_label">运行时长：</div><div class="info_right_label"><span>{{ data.sys_running_time }}</span>&nbsp;</div></div>
				<div class="right_info"><div class="info_left_label">CPU使用率：</div><div class="info_right_label"><span>{{ data.sys_rateof_cpu }}</span></div></div>
	    		<div class="right_info"><div class="info_left_label">本地时间：</div><div class="info_right_label"><span>{{ data.sys_local_time|date:"Y-m-d H:i:s" }}</span></div></div>
	    		<div class="right_info"><div class="info_left_label">出厂日期：</div><div class="info_right_label"><span>{{ data.sys_out_time|date:"Y-m-d H:i:s" }}</span></div></div>
	    	</div>
		</fieldset>
		<fieldset class="system system_0203">
	    	<legend><p>內存</p></legend>
	    	<div id="left_div">
		    	<div class="left_info"><div class="info_left_label">内存大小：</div><div class="info_right_label"><span>{{ data.sys_memory_size }}</span></div></div>
		    	<div class="left_info"><div class="info_left_label">硬盘总量：</div><div class="info_right_label"><span>{{ data.sys_harddisk_size }}</span></div></div>
		   		<div class="left_info"><div class="info_left_label">USB接口：</div><div class="info_right_label"><span>{{ data.sys_usb_num }}</span>&nbsp;&nbsp;&nbsp;&nbsp;个</div></div>
		    </div>
	    	<div id="right_div">
	    		<div class="right_info"><div class="info_left_label">内存剩余：</div><div class="info_right_label"><span>{{ data.sys_memory }}</span></div></div>
	    		<div class="right_info"><div class="info_left_label">硬盘剩余：</div><div class="info_right_label"><span>{{ data.sys_harddisk }}</span></div></div>
	    		<div class="right_info"><div class="info_left_label">RS232接口：</div><div class="info_right_label"><span>{{ data.sys_rs232_num }}</span>&nbsp;&nbsp;&nbsp;&nbsp;个</div></div>
	    	</div>
		</fieldset>
		<fieldset class="system system_0203">
	    	<legend><p>网络</p></legend>
	    	<div id="left_div">
		    	<div class="left_info"><div class="info_left_label">IP地址：</div><div class="info_right_label">{{ data.sys_ip }}</div></div>
		    	<div class="left_info"><div class="info_left_label">子网掩码：</div><div class="info_right_label">{{ data.sys_mask }}</div></div>
		    	<div class="left_info"><div class="info_left_label">MAC地址：</div><div class="info_right_label">{{ data.sys_mac }}</div></div>
	    	</div>
	    	<div id="right_div">
	    		<div class="right_info"><div class="info_left_label">连接状态：</div><div class="info_right_label">{{ data.get_sys_net_status_display }}</div></div>
	    		<div class="right_info"><div class="info_left_label">默认网关：</div><div class="info_right_label">{{ data.sys_gateway }}</div></div>
	    	</div>
		</fieldset>
	</body>
</html>