apps/m5/urls.py
from django.conf.urls import url
# from wangguang import views
from apps.m5 import views

app_name = 'apps.m5'
urlpatterns = [
    url(r'^manage$', views.M5ManageView.as_view(), name='m5manage'),  # 注册页面
    url(r'^manage/(?P<m5device_name>\w+)$', views.M5DeviceManageView.as_view(), name='devicemanage'),  # 单个设备管理页面
    url(r'^manage/devicedebug/(?P<m5device_name>\w+)$', views.M5DeviceDebugView.as_view(), name='devicededug'),  # 单个设备管理页面
    url(r'^manage/devicedataforward/(?P<m5device_name>\w+)$', views.M5DeviceDataView.as_view(), name='devicedataforward'),  # 单个设备管理页面

]

edgebox_web/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.user.views import LoginView
from apps.shebei.views import DeviceView
from django.contrib.auth.decorators import login_required

name="main"
urlpatterns = [

    path('apidata/',include('apps.apidata.urls', namespace='apidata')),
    path('admin/', admin.site.urls),
    # path('search/', include('haystack.urls')),  # 全文检索框架
    path('user/', include('apps.user.urls', namespace='user')),  # 用户登录注册模块
    path('wangguang/', include('apps.wangguang.urls', namespace='wangguang')),  # 网关管理模块
    path('m5/', include('apps.m5.urls', namespace='m5')),  # m5扩展模块
    path('shebei/', include('apps.shebei.urls', namespace='shebei')),  # 设备管理模块
    path('yuancheng/', include('apps.yuancheng.urls', namespace='yuancheng')),  # 远程管理模块
    path('loginfo/', include('apps.loginfo.urls', namespace='loginfo')),  # 日志管理模块
    path('qudong/', include('apps.qudong.urls', namespace='qudong')),  # 驱动管理模块
    path('login/', LoginView.as_view(), name="login"),  # 登录页面
    path('accounts/login/', LoginView.as_view(), name="login"),  # 登录页面
    path('', LoginView.as_view()),  # 登录页面
    path('index/', login_required(DeviceView.as_view()), name="index"),  # 主页(登录验证)
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]

apps/m5/models.py
from django.db import models

# Create your models here.

apps/shebei/models.py
import datetime

from django.db import models
from db.base_model import BaseModel
# Create your models here.


class SubDevice(BaseModel):
    '''子设备列表模型类'''
    ENABLE_CHOICES=(
        (0, "未启用"),
        (1, "启用")
    )
    STATUS_CHOICES=(
        (0, "离线"),
        (1, "在线"),
    )
    subdevice_name= models.CharField(max_length=30, verbose_name="子设备名称")
    subdevice_key= models.CharField(default="", max_length=100, verbose_name="子设备id")
    subdevice_secret= models.CharField(default="", max_length=200, verbose_name="子设备secret")
    subdevice_position= models.CharField(max_length=30, verbose_name="子设备位置")
    subdevice_model= models.CharField(max_length=30, verbose_name="子设备型号")
    subdevice_type= models.CharField(max_length=30, verbose_name="子设备类型")
    subdevice_remark= models.CharField(max_length=50, verbose_name="子设备描述")
    subdevice_online_time= models.DateTimeField(auto_now_add=True, verbose_name="最近上线时间")
    subdevice_status= models.SmallIntegerField(default=0, choices=STATUS_CHOICES, verbose_name="子设备运行状态")
    subdevice_enable= models.SmallIntegerField(default=1, choices=ENABLE_CHOICES, verbose_name="子设备激活使能")

    class Meta:
        db_table = 'gateway_subdevice_list'
        verbose_name = '网关子设备列表信息'
        verbose_name_plural = verbose_name


class DataTransmitList(BaseModel):
    '''子设备列表模型类'''
    TYPE=(
        (0, "CorePro"),
        (1, "MQTT"),
        (2, "KAFKA"),
        (3, "DB"),
    )
    TYPE_DICT_F = { "MQTT":0, "CorePro":1,"KAFKA":2,"DB":3}
    TYPE_DICT = { 0:"MQTT", 1:"CorePro",2:"KAFKA",3:"DB"}
    STATUS_DICT = { 0:"正在运行", 1:"已禁用",2:"转发出错",3:"转发停止"}

    STATUS = (
        (0, "正在运行"),
        (1, "已禁用"),
        (2, "运行异常"),
        (3, "转发停止"),
    )
    ENABLE_CHOICES = (
        (0, "关闭"),
        (1, "启用")
    )
    subdevice = models.ForeignKey('shebei.SubDevice', to_field='id', on_delete=models.CASCADE, verbose_name='子设备id')
    transmit_type = models.SmallIntegerField(default=0, choices=TYPE, verbose_name="转发类型")
    transmit_status = models.SmallIntegerField(default=1, choices=STATUS, verbose_name="转发状态")
    transmit_name = models.CharField(default="通道xx",max_length=30, verbose_name="转发名称")
    transmit_remark = models.CharField(default="通道xx",max_length=30, verbose_name="转发描述")
    transmit_ip = models.CharField(default="",max_length=30, verbose_name="转发ip")
    transmit_port = models.CharField(default="",max_length=30, verbose_name="转发port")
    transmit_username = models.CharField(default="",max_length=100, verbose_name="转发用户")
    transmit_password = models.CharField(default="",max_length=100, verbose_name="转发密码")
    transmit_topic = models.CharField(default="",max_length=100, verbose_name="转发主题或表")
    transmit_number= models.IntegerField(default=0, verbose_name="子设备上传消息数")
    transmit_enable= models.SmallIntegerField(default=0, choices=ENABLE_CHOICES, verbose_name="子设备激活使能")

    class Meta:
        db_table = 'gateway_transmit_list'
        verbose_name = '网关子设备数据转发通道'
        verbose_name_plural = verbose_name

apps/m5/views.py
import json

from django.shortcuts import render
from django.views.generic import View
from django.forms.models import model_to_dict
# Create your views here.t
from random import randint
from django_redis import get_redis_connection
from apps.apidata.models import M5Data
# /m5/manage
class M5ManageView(View):
    '''网关管理'''
    def get(self, request):
        m5_devices=[]
        conn = get_redis_connection('default')
        m5 = "m5_*"
        devices = conn.keys(m5)
        for m5 in devices:
            b_info=conn.hgetall(m5.decode())
            info={}
            for i,value in b_info.items():
                key = i.decode()
                info[key]=value.decode()
                if key == "m5device_name":
                    info[key]="m5_"+info[key]
            m5_devices.append(info)
        print(m5_devices)
        # m5_devices["m5device_name"] = "m5_"+m5_devices["m5device_name"]
        # context = {
        #     "m5_devices": m5_devices
        # }

        return render(request, 'm5/M5_Pair_Connection.html', locals() )

# /m5/manage/<device_id>
class M5DeviceManageView(View):
    '''M5设备的管理主页面'''
    def get(self, request, m5device_name):
        conn = get_redis_connection('default')
        # m5="m5_%s" % m5device_name
        b_info = conn.hgetall(m5device_name)
        info = {}
        for i, value in b_info.items():
            key = i.decode()
            info[key] = value.decode()
            if key == "m5device_name":
                info[key] = "m5_" + info[key]
        print(info)
        context = {
            "info": info
        }
        return render(request, 'm5/M5_Docking_Module_Main.html', context)


# TODO(Jianli) /m5/manage/devicedebug/<device_id>

class M5DeviceDebugView(View):
    '''M5设备的特征提取页面'''
    def get(self, request, m5device_name):
        print(m5device_name)
        data=M5Data.objects.filter(subdevice_name=m5device_name).order_by("-id")[0]
        data=json.loads(data.data)
        # data=data["m5device_forward"][0]
        print(data)
        return render(request, 'm5/Feature_Extraction.html', locals())


# /m5/manage/devicedataforward/<device_id>
class M5DeviceDataView(View):
    '''M5设备的数据转发页面'''

    def get(self, request, m5device_name):
        m5paths = []
        conn = get_redis_connection('default')
        m5path_key = "m5path_%s_*" % m5device_name.split("_")[1]
        b_paths = conn.keys(m5path_key)
        for path in b_paths:
            b_info = conn.hgetall(path.decode())
            info = {}
            for i, value in b_info.items():
                info[i.decode()] = value.decode()
            m5paths.append(info)
        context = {
            "m5paths": m5paths
        }
        print(m5paths)
        return render(request, 'm5/Data_Forwarding.html', context)

templates/m5/Data_Forwarding.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" href="{% static 'css/pop.css' %}" />
		<link rel="stylesheet" href="{% static 'css/table.css' %}" />
		<link rel="stylesheet" href="{% static 'css/font.css' %}" />
		<link rel="stylesheet" href="{% static 'css/sub_manage/Data_Forwarding.css' %}" />
	</head>
	<body>
		<div id="data_add" class="div_font_css div_cursor" onclick="clickAdd('data_add_podiv')">
			<img src="{% static 'img/gateway/gateway_pop/u44.png' %}" />&nbsp;&nbsp;&nbsp;<span class="font_blue">新增转发</span>
		</div>
		<div id="data_table_div">
			<table id="data_table" cellpadding="0" cellspacing="0">
				<thead id="data_thead">
					<td style="width: 70px;">序号</td>
					<td style="width: 120px;">转发路径名称</td>
					<td style="width: 110px;">启用/关闭</td>
					<td>运行状态</td>
					<td>上行消息数</td>
					<!--<td>创建时间</td>-->
					<td style="width: 150px;">描述</td>
					<td style="width: 150px;">操作</td>
				</thead>
				{% for m5path in m5paths %}
					<tr class='data_tr'>
						<td>{{ forloop.counter }}</td>
						<td><p class='data_name'>{{ m5path.m5path_name }}</p></td>
						<td>
							<div class='data_button_div'>
								<div class='data_enable_content'>
									<span class='data_enable_span'>{{ m5path.m5path_enable }}</span>
								</div>
								{% if m5path.m5path_enable == "启用"  %}
									<div  style="background:rgba(0, 159, 60, 1)" class='data_enable_button' onclick=''>
									<div style='display:block' class='data_button_on'>ON</div>
									<div style='display:None'  class='data_button_off'>OFF</div>
									<div style="right: 0" class='data_button_circular'></div>
									</div>
								{% else %}
									<div  style="background:rgba(188, 188, 188, 1)" class='data_enable_button' onclick=''>
									<div style='display:None' class='data_button_on'>ON</div>
									<div style='display:block'  class='data_button_off'>OFF</div>
									<div style="left: 1px" class='data_button_circular'></div>
									</div>
								{% endif %}
							</div>
						</td>
						<td id="status" class="status">{{ m5path.m5path_status }}</td>
						<td class="count" id="count"  >{{ m5path.m5path_count }}</td>


						<td>{{ m5path.m5path_remark }}</td>
						<td style='position: relative;'>
							<div class='data_details div_cursor' onclick="data_details('{{ transmit.transmit_name }}','{{ transmit.get_transmit_type_display }}','{{ transmit.transmit_topic }}')">详情</div>
							<div class='data_edit div_cursor' onclick='data_click_edit("{{ transmit.id }}","{{ transmit.transmit_name }}","{{ transmit.transmit_type }}","{{ transmit.transmit_ip }}","{{ transmit.transmit_port }}","{{ transmit.transmit_username }}","{{ transmit.transmit_password }}","{{ transmit.transmit_topic }}", {{ transmit.TYPE_DICT }},"{{ transmit.transmit_remark }}" )'>编辑</div>
							<div class='data_delete div_cursor' onclick='data_delete("{{ transmit.id }}")'>删除</div>
						</td>
					</tr>
				{% empty %}
					<tr>
						<td colspan="7">No matching records found</td>
					</tr>
				{% endfor %}
			</table>
		</div>
		
		
		
		<div id="podiv_tips">
			<div id="mana" class="bu_tips_div">
				<div id="bu_tips_img"><img src="{% static 'img/sub_manage/u636.png' %}"/></div>
				<div id="bu_tips_content"><p>操作成功 ！</p></div>
			</div> 
			<div id="dele" class="bu_tips_div">
				<div id="bu_tips_img"><img src="{% static 'img/sub_manage/u636.png' %}"/></div>
				<div id="bu_tips_content"><p>删除成功 ！</p></div>
			</div>
		</div>

		
		<script type="text/javascript" src="{% static 'js/jquery.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/pop.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/operation_clue.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/sub_manage/Data_Forwarding.js' %}" ></script>
	</body>
</html>

templates/m5/M5_Docking_Module_Main.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" href="{% static 'css/page.css' %}" />
		<link rel="stylesheet" href="{% static 'css/pop.css' %}" />
		<link rel="stylesheet" href="{% static 'css/Small_Main.css' %}" />
		<link rel="stylesheet" href="{% static 'css/iframe.css' %}" />
		<link rel="stylesheet" href="{% static 'css/font.css' %}" />
		<!--<link rel="stylesheet" href="{% static 'css/overflow.css" />-->
	</head>
	<body>
		<div class="gateway_top">
			<div class="page_tittle">
				<span><span class="div_cursor" onclick="BackParent('{% url 'm5:m5manage' %}')">对接通道</span>&nbsp;&nbsp;&nbsp;>&nbsp;&nbsp;&nbsp;&nbsp;<span id="log_sub_title">特征提取</span></span>
			</div>
		</div>
		<div id="docking_small" class="smallMenu">
			<a style="text-decoration: none;">
				<div class="menu" onclick="clickDiv('menu',0,5)" onmouseover="over('menu',0);overM(5,0, '{{ info.m5device_name }}' )" onmouseout="out('menu',0)">
					<div class="smallMenu_div_word">特征提取&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&gt;</div>
				</div>
			</a>
			<a style="text-decoration: none;">
				<div class="menu" onclick="clickDiv('menu',1,5)" onmouseover="over('menu',1);overM(5,1,'{{ info.m5device_name }}' )" onmouseout="out('menu',1)">
					<div class="smallMenu_div_word">数据转发&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&gt;</div>
				</div>
			</a>
		</div>
		<iframe id="docking_iframe" class="css_iframe" name="docking_iframe" src="{% url 'm5:devicededug' info.m5device_name %}"></iframe>
		
		
		<div id="podiv">
			<form action="" method="post">
				<div id="data_add_podiv" class="gateway_service div_shadow div_backgr">
					<div class="pop_top">
						<div class="pop_img"><img src="{% static 'img/gateway/gateway_pop/u44.png' %}" /></div>
						<div class="pop_tittle text_left"><span class="tittle_label" style="font-size: 16px;">新增转发路径</span></div>
						<div class="pop_close u2040 div_cursor" onclick="pop_close('data_add_podiv')"><img src="{% static 'img/gateway/gateway_pop/u2040.png' %}" /></div>
					</div>
					
					<div class="pop_line"><img src="{% static 'img/gateway/u130.png' %}" width="470px" /></div>
					<div class="pop_message">
						<div class="pop_content">
							<div class="pop_label">
								<span><sup class="font_red">*</sup>转发路径名称：</span>
							</div>
							<div class="pop_data_add_input_div">
								<input class="pop_data_add_input" type="text" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span><sup class="font_red">*</sup>转发类型：</span>
							</div>
							<div class="pop_data_add_input_div">
								<select>
									<option>MQTT</option>
									<option>KAFKA</option>
									<option>DB</option>
								</select>
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span><sup class="font_red">*</sup>Topic：</span>
							</div>
							<div class="pop_data_add_input_div">
								<input class="pop_data_add_input" type="text" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span>是否鉴权：</span>
							</div>
							<div class="pop_data_add_input_div">
								<div class="data_radio"><input type="radio" name="authentication" checked="checked" onclick="radioClick(false)" /><span>否</span></div>
								<div class="data_radio"><input type="radio" name="authentication" onclick="radioClick(true)" /><span>是</span></div>
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span id="forwarding_ip">IP：</span>
							</div>
							<div class="pop_data_add_input_div">
								<input class="pop_data_add_input" type="text" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span id="forwarding_port">端口号：</span>
							</div>
							<div class="pop_data_add_input_div">
								<input class="pop_data_add_input" type="text" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span id="forwarding_userName">User Name：</span>
							</div>
							<div class="pop_data_add_input_div">
								<input class="pop_data_add_input" type="text" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span id="forwarding_password">Password：</span>
							</div>
							<div class="pop_data_add_input_div">
								<input class="pop_data_add_input" type="text" />
							</div>
						</div>
						
						<div id="data_test_div" class="test_submit div_cursor text_center"  onclick="pop_save('data_add_podiv')"><span>测试</span></div>
						<div id="data_submit_div" class="new_submit div_cursor text_center"  onclick="pop_save('data_add_podiv')"><span>確定</span></div>
						<div id="data_close_div" class="new_close div_cursor text_center" onclick="pop_close('data_add_podiv')"><span>取消</span></div>
					</div>
				</div>
			</form>
		
			<form action="" method="post">
				<div id="data_details" class="gateway_service div_position div_shadow div_backgr">
					<div class="pop_top">
						<div class="pop_img"><img src="{% static 'img/gateway/gateway_pop/u44.png' %}" height="18px" width="20px" /></div>
						<div class="pop_tittle text_left"><span class="tittle_label" style="font-size: 16px;">数据转发详情</span></div>
						<div class="pop_close u2040 div_cursor" onclick="pop_close('data_details')"><img src="{% static 'img/gateway/gateway_pop/u2040.png' %}" /></div>
					</div>
					
					<div class="pop_line"><img src="{% static 'img/gateway/u130.png' %}" width="440px" /></div>
					<div class="pop_message" style="top: 80px;">
						<div class="pop_content">
							<div class="pop_label">
								<span>转发路径名称：</span>
							</div>
							<div class="pop_data_details_input_div">
								<input class="pop_data_details_input" type="text" value="test-1" />
							</div>
						</div>	
						<div class="pop_content">
							<div class="pop_label">
								<span>转发类型：</span>
							</div>
							<div class="pop_data_details_input_div">
								<input class="pop_data_details_input" type="text" value="CorePro" />
							</div>
						</div>	
						<div class="pop_content">
							<div class="pop_label">
								<span>消息上行数：</span>
							</div>
							<div class="pop_data_details_input_div">
								<input class="pop_data_details_input" type="text" value="10" />
							</div>
						</div>	
						<div class="pop_content">
							<div class="pop_label" style="top: 80px;">
								<span>消息"payload"：</span>
							</div>
							<div class="pop_data_details_input_div">
								<div class="pop_data_details_span">
									<span>
										{
										<br />
											&nbsp;&nbsp;"设备名称"："<span id="device_name">LiChuang</span>"
											<br />
											&nbsp;&nbsp;"设备类型"："<span id="device_name">力创三相电表</span>"
											<br />
											&nbsp;&nbsp;"设备位置"："<span id="device_name">E6-2F</span>"
											<br />
											&nbsp;&nbsp;"设备型号"："<span id="device_name">JUYOUWETY</span>"
											<br />
											&nbsp;&nbsp;"设备描述"："<span id="device_name">力创智能电表</span>"	
										<br />
										}
									</span>
								</div>
							</div>
						</div>	
					</div>
				</div>
			</form>
			
			<form action="" method="post">
				<div id="data_edit_podiv" class="gateway_service div_position div_shadow div_backgr">
					<div class="pop_top">
						<div class="pop_img"><img src="{% static 'img/gateway/gateway_pop/u44.png' %}" /></div>
						<div class="pop_tittle text_left"><span class="tittle_label" style="font-size: 16px;">编辑转发路径</span></div>
						<div class="pop_close u2040 div_cursor" onclick="pop_close('data_edit_podiv')"><img src="{% static 'img/gateway/gateway_pop/u2040.png' %}" /></div>
					</div>
					
					<div class="pop_line"><img src="{% static 'img/gateway/u130.png' %}" width="470px" /></div>
					<div class="pop_message">
						<div class="pop_content">
							<div class="pop_label">
								<span><sup class="font_red">*</sup>转发路径名称：</span>
							</div>
							<div class="pop_data_add_input_div">
								<input class="pop_data_add_input" type="text" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span><sup class="font_red">*</sup>转发类型：</span>
							</div>
							<div class="pop_data_add_input_div">
								<select>
									<option>MQTT</option>
									<option>KAFKA</option>
									<option>DB</option>
								</select>
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span><sup class="font_red">*</sup>Topic：</span>
							</div>
							<div class="pop_data_add_input_div">
								<input class="pop_data_add_input" type="text" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span>是否鉴权：</span>
							</div>
							<div class="pop_data_add_input_div">
								<div class="data_radio"><input type="radio" name="authentication_update" checked="checked" onclick="radioClick_update(false)" /><span>否</span></div>
								<div class="data_radio"><input type="radio" name="authentication_update" onclick="radioClick_update(true)" /><span>是</span></div>
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span id="forwarding_update_ip">IP：</span>
							</div>
							<div class="pop_data_add_input_div">
								<input class="pop_data_add_input" type="text" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span id="forwarding_update_port">端口号：</span>
							</div>
							<div class="pop_data_add_input_div">
								<input class="pop_data_add_input" type="text" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span id="forwarding_update_userName">User Name：</span>
							</div>
							<div class="pop_data_add_input_div">
								<input class="pop_data_add_input" type="text" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label">
								<span id="forwarding_update_password">Password：</span>
							</div>
							<div class="pop_data_add_input_div">
								<input class="pop_data_add_input" type="text" />
							</div>
						</div>
						
						<div id="data_test_div" class="test_submit div_cursor text_center"  onclick="pop_save('data_edit_podiv')"><span>测试</span></div>
						<div id="data_submit_div" class="new_submit div_cursor text_center"  onclick="pop_save('data_edit_podiv')"><span>確定</span></div>
						<div id="data_close_div" class="new_close div_cursor text_center" onclick="pop_close('data_edit_podiv')"><span>取消</span></div>
					</div>
				</div>
			</form>
			
			
			<div id="pop_delete" class="div_backgr">
				<div class="pop_submit_img"><img src="{% static 'img/gateway/gateway_pop/u387.png' %}" /></div>
				<div class="pop_tips"><span class="font_orange">温馨提示</span></div>
				<div class="pop_line text_left"><img src="{% static 'img/gateway/gateway_pop/u363.png' %}" width="300px" /></div>
						
				<div id="delete_pop_sub" class="backgr_color"><span>确定删除选择的设备吗？</span></div>
				<div id="list_delete_submit" class="new2_submit div_cursor text_center"  onclick="pop_delete_content('docking_iframe')"><p>確定<p></div>
				<div id="list_delete_close" class="new2_close div_cursor text_center" onclick="pop_close('pop_delete')"><p>取消</p></div>
			</div>
		</div>
		
		
		<script type="text/javascript" src="{% static 'js/jquery1.3.2.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/page.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/pop.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/Back.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/Docking_Module/M5_Docking_Module_Main.js' %}" ></script>
	</body>
</html>