apps/qudong/urls.py
from django.urls import path, include
from django.conf.urls import url
from apps.qudong import views

app_name = 'apps.qudong'
urlpatterns = [
    url(r'^manage', views.QudongManageView.as_view(), name='qudongmanage'),  #
    url(r'^drive', views.QudongDriveView.as_view(), name='qudongdrive'),  #
    url(r'^template', views.QudongTemplateView.as_view(), name='qudongtemplate'),  #

]

edgebox_web/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.user.views import LoginView
from apps.shebei.views import DeviceView
from django.contrib.auth.decorators import login_required

name="main"
urlpatterns = [

    path('apidata/',include('apps.apidata.urls', namespace='apidata')),
    path('admin/', admin.site.urls),
    # path('search/', include('haystack.urls')),  # 全文检索框架
    path('user/', include('apps.user.urls', namespace='user')),  # 用户登录注册模块
    path('wangguang/', include('apps.wangguang.urls', namespace='wangguang')),  # 网关管理模块
    path('m5/', include('apps.m5.urls', namespace='m5')),  # m5扩展模块
    path('shebei/', include('apps.shebei.urls', namespace='shebei')),  # 设备管理模块
    path('yuancheng/', include('apps.yuancheng.urls', namespace='yuancheng')),  # 远程管理模块
    path('loginfo/', include('apps.loginfo.urls', namespace='loginfo')),  # 日志管理模块
    path('qudong/', include('apps.qudong.urls', namespace='qudong')),  # 驱动管理模块
    path('login/', LoginView.as_view(), name="login"),  # 登录页面
    path('accounts/login/', LoginView.as_view(), name="login"),  # 登录页面
    path('', LoginView.as_view()),  # 登录页面
    path('index/', login_required(DeviceView.as_view()), name="index"),  # 主页(登录验证)
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]

apps/qudong/models.py
from django.db import models
from db.base_model import BaseModel

# Create your models here.


class Drive(BaseModel):
    '''驱动程序管理模型类'''
    drive_name= models.CharField(max_length=30, verbose_name="驱动名称")
    drive_path= models.CharField(max_length=150, verbose_name="驱动路径")
    drive_remark= models.CharField(max_length=150, verbose_name="驱动描述")

    class Meta:
        db_table = 'gateway_drive_list'
        verbose_name = '网关子设备列表信息'
        verbose_name_plural = verbose_name

# 模板信息
class ModbusRtuModel(BaseModel):
    '''ModBus Rtu 协议配置模型 对应设备模板库 以及采集协议配置表单'''
    PARITY_CHECK_CHOICES= (
        (0, "ODD"),
        (1, "EVEN"),
        (2, "无校验"),
    )
    RULE_CHOICES= (
        (0, "长整型"),
        (1, "IEEE-754")
    )
    SHOW_CHOICES= (
        (0, "不显示至设备模板列表"),
        (1, "显示至设备模板列表")
    )
    # subdevice_id= models.IntegerField(verbose_name="子设备id")
    subdevice= models.ForeignKey('shebei.SubDevice', to_field='id', on_delete=models.CASCADE, verbose_name='子设备id')
    accord_name = models.CharField(max_length=30, verbose_name="协议名称")
    accord_type = models.CharField(max_length=30, verbose_name="协议类型")
    accord_address = models.CharField(max_length=30, verbose_name="协议地址位")
    accord_com= models.CharField(max_length=30, verbose_name="协议串口号")
    accord_botelv= models.CharField(default="9600", max_length=30, verbose_name="协议波特率")
    accord_databit= models.SmallIntegerField(default=8, verbose_name="协议数据位")
    accord_stopbit= models.SmallIntegerField(default=1, verbose_name="协议停止位")
    accord_check= models.SmallIntegerField(default=2, choices=PARITY_CHECK_CHOICES, verbose_name="协议奇偶校验")
    accord_timeout= models.CharField(max_length=30, verbose_name="协议响应时间")
    accord_readcycle= models.CharField(max_length=30, verbose_name="协议读取周期")
    accord_cmd= models.CharField(max_length=2000, verbose_name="协议指令列表")
    accord_rule= models.SmallIntegerField(default=0, choices=RULE_CHOICES, verbose_name="协议数据转换公式")

    is_show= models.SmallIntegerField(default=0, choices=SHOW_CHOICES, verbose_name="显示标识" )

    class Meta:
        db_table = 'gateway_modbusrtu_models'
        verbose_name = 'ModBusRtu协议配置模型'
        verbose_name_plural = verbose_name


# 设备模板库 modebus
class EquipmentTemplateRtu(BaseModel):
    '''
    ModeBus Rtu 设备模板库Rtu 表 简称 etr
    '''
    FORMAT_DICT = { "Hex": 0, "Long-int": 1, "IEEE-754": 2}
    FORMAT_CHOICES = (
        (0, "Hex"),
        (1, "Long-int"),
        (2, "IEEE-754")
    )
    etr_name        = models.CharField(max_length=30, verbose_name="模板名称")
    etr_remark      = models.CharField(max_length=30, verbose_name="模板描述")
    etr_accordname  = models.CharField(max_length=30, default="ModeBus-RTU", verbose_name="模板协议名称")
    etr_cmdid       = models.CharField(max_length=30, verbose_name="模板下发设备指令id")
    etr_cmdregister = models.CharField(max_length=30, verbose_name="模板下发设备寄存器地址")
    etr_cmdnumber   = models.CharField(max_length=30, verbose_name="模板下发设备寄存器个数")
    etr_param       = models.CharField(max_length=50, verbose_name="模板返回设备数据的参数名")
    etr_format      = models.SmallIntegerField(default=0, choices=FORMAT_CHOICES, verbose_name="模板返回设备数据格式")
    etr_rule        = models.CharField(max_length=30, verbose_name="模板返回数据计算公式")

    class Meta:
        db_table = 'gateway_equipmenttemplatertu'
        verbose_name = 'ModBusRtu设备模板库'
        verbose_name_plural = verbose_name

apps/qudong/views.py
from django.shortcuts import render
from django.views.generic import View

# qudong/manage
class QudongManageView(View):
    '''驱动管理'''
    def get(self, request):

        return render(request, 'qudong/Library_Main.html' )

# qudong/manage/drive
class QudongDriveView(View):
    '''驱动列表'''
    def get(self, request):

        return render(request, 'qudong/Driver_Library.html')
        # return render(request, 'qudong/Template_Library.html')


# qudong/manage/template
class QudongTemplateView(View):
    '''驱动列表'''
    def get(self, request):

        # return render(request, 'qudong/Driver_Library.html')
        return render(request, 'qudong/Template_Library.html')

templates/qudong/Driver_Library.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" href="{% static 'css/img.css' %}" />
		<link rel="stylesheet" href="{% static 'css/table.css' %}" />
		<link rel="stylesheet" href="{% static 'css/font.css' %} " />
		<link rel="stylesheet" href="{% static 'css/dev_dri_library/Driver_Library.css' %} " />
	</head>
	<body>
		<div id="driver_add_img" class="operation div_cursor" onclick="clickAdd('driver_add_div')">
			<img src="{% static 'img/gateway/gateway_pop/u44.png' %}" />&nbsp;&nbsp;&nbsp;<span>新增驱动库</span>
		</div>
		
		<div id="driver_table_div">
			<table id="driver_table" cellpadding="0" cellspacing="0">
				<thead id="driver_thead">
					<td width="160px">驱动库名称</td>
					<td width="200px">创建时间</td>
					<td>描述</td>
					<td width="130px">操作</td>
				</thead>
				<tr>
					<td>ModBus</td>
					<td>2019-05-25 13:52:47</td>
					<td>ModBus采集程式</td>
					<td><span class="font_red">删除</span></td>
				</tr>
				<tr>
					<td>CNC</td>
					<td>2019-04-12 09:48:36</td>
					<td>CNC采集程式</td>
					<td><span class="font_red">删除</span></td>
				</tr>
				<tr>
					<td>SMT</td>
					<td>2019-04-10 10:52:32</td>
					<td>SMT采集程式</td>
					<td><span class="font_red">删除</span></td>
				</tr>
				<tr>
					<td>IO</td>
					<td>2019-03-25 09:14:40</td>
					<td>IO采集程式</td>
					<td><span class="font_red">删除</span></td>
				</tr>
			</table>
		</div>
		
		<script type="text/javascript" src="{% static 'js/click_event.js' %}" ></script>
	</body>
</html>

templates/qudong/Library_Main.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" href="{% static 'css/iframe.css' %}" />
		<link rel="stylesheet" href="{% static 'css/Small_Main.css' %}" />
		<link rel="stylesheet" href="{% static 'css/page.css' %}" />
		<link rel="stylesheet" href="{% static 'css/pop.css' %}" />
		<link rel="stylesheet" href="{% static 'css/font.css' %}" />
		<!--<link rel="stylesheet" href="{% static 'css/overflow.css' %}" />-->
		
	</head>
	<body>
		<div class="gateway_top">
			<div class="page_tittle">
				<span><span>设备驱动库</span> &nbsp;&nbsp;&nbsp;&gt;&nbsp;&nbsp;&nbsp;<span id="log_sub_title">驱动库</span></span>
			</div>
		</div>
		<div id="library_smallMenu" class="smallMenu">
			<a style="text-decoration: none;" onclick="clickDiv('menu',0,4)" onmouseover="over('menu',0);overM('menu',0)" onmouseout="out('menu',0)">
				<div class="menu">
					<div class="smallMenu_div_word">驱动库&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&gt;</div>
				</div>
			</a>
			<a style="text-decoration: none;" onclick="clickDiv('menu',1,4)" onmouseover="over('menu',1);overM('menu',1)" onmouseout="out('menu',1)">
				<div class="menu">
					<div class="smallMenu_div_word">模板库&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&gt;</div>
				</div>
			</a>
		</div>


		<iframe id="library_iframe" class="css_iframe" name="library_iframe" src="{% url 'qudong:qudongdrive' %}"></iframe>
		
		<div id="podiv">
			
			<form name="" action="" method="post">
				<div id="driver_add_div" class="div_radius div_shadow">
					<div class="pop_top">
						<div class="pop_img"><img src="{% static 'img/gateway/gateway_pop/u44.png' %}" /></div>
						<div class="pop_tittle text_left"><span class="tittle_label">新增驱动库</span></div>
						<div class="pop_close div_cursor" onclick="pop_close('driver_add_div')"><img src="{% static 'img/gateway/gateway_pop/u2040.png' %}" /></div>
					</div>
				
					<div class="pop_line"><img src="{% static 'img/gateway/u130.png' %}" width="410px" /></div>
				
					<div class="pop_message">
						<div class="pop_content">
							<div class="pop_label2">
								<span><sup class="font_red">*</sup>驱动库名称：</span>
							</div>
							<div class="driver_input_div">
								<input id="driver_input_name" type="text" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label2">
								<span><sup class="font_red">*</sup>驱动库文件：</span>
							</div>
							<div class="driver_input_div">
								<input class="gateway_input" type="file" />
							</div>
						</div>
						<div class="pop_content">
							<div class="pop_label2">
								<span>驱动库描述：</span>
							</div>
							<div class="driver_input_div">
								<textarea id="driver_discribe"></textarea>
							</div>
						</div>
						<div id="driver_submit_div" class="new_submit div_cursor text_center"  onclick="pop_save('driver_add_div')"><p>保存<p></div>
						<div id="driver_close_div" class="new_close div_cursor text_center" onclick="pop_close('driver_add_div')"><p>取消</p></div>
					</div>
				</div>
			</form>
			
		</div>
		
		
		<script type="text/javascript" src="{% static 'js/jquery.js' %}" ></script>		
		<script type="text/javascript" src="{% static 'js/page.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/pop.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/dev_dri_library/Library_Main.js' %}" ></script>
	</body>
</html>

templates/qudong/Template_Library.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		
		<link rel="stylesheet" href="{% static 'css/table.css' %} " />
		<link rel="stylesheet" href="{% static 'css/font.css' %} " />
		<link rel="stylesheet" href="{% static 'css/dev_dri_library/Driver_Library.css' %} " />
	</head>
	<body>
		<div id="driver_table_div">
			<table id="driver_table" cellpadding="0" cellspacing="0">
				<thead id="driver_thead">
					<td width="120px">设备类型</td>
					<td width="120px">协议类型</td>
					<td width="120px">协议名称</td>
					<td width="160px">创建时间</td>
					<td width="160px">描述</td>
					<td width="130px">操作</td>
				</thead>
				<tr>
					<td>HC31A电表</td>
					<td>RS485</td>
					<td>ModBus</td>
					<td>2019-05-25 13:52:47</td>
					<td>HC31A电表配置模板</td>
					<td><span class="font_red">删除</span></td>
				</tr>
				<tr>
					<td>HC31A电表</td>
					<td>RS485</td>
					<td>ModBus</td>
					<td>2019-04-12 09:48:36</td>
					<td>HC33A电表配置模板</td>
					<td><span class="font_red">删除</span></td>
				</tr>
				<tr>
					<td>SMT API</td>
					<td>RS485</td>
					<td>SMT协议</td>
					<td>2019-04-10 10:52:32</td>
					<td>SMT API配置模板</td>
					<td><span class="font_red">删除</span></td>
				</tr>
				<tr>
					<td>IO</td>
					<td>RS485</td>
					<td>IO协议</td>
					<td>2019-03-25 09:14:40</td>
					<td>IO 配置模板</td>
					<td><span class="font_red">删除</span></td>
				</tr>
			</table>
		</div>
	</body>
</html>