apps/shebei/urls.py
from django.conf.urls import url
# from shebei import views
from apps.shebei import views

# app_name = 'shebei'
app_name = 'apps.shebei'
urlpatterns = [
    url(r'^devicelist$', views.DeviceListView.as_view(), name='devicelist'),  # 设备列表页面
    url(r'^devicemanage/(?P<device_id>\d+)$', views.DeviceManageView.as_view(), name='devicemanage'),  # 单个设备管理页面
    url(r'^devicemanage/deviceinfo/(?P<device_id>\d+)$', views.DeviceInfoView.as_view(), name='deviceinfo'),  # 单个设备基本信息页面
    url(r'^devicemanage/deviceprotocol/(?P<device_id>\d+)$', views.DeviceProtocolView.as_view(), name='deviceprotocol'),  # 单个设备协议配置页面
    url(r'^deviceprotocol/apply$', views.DeviceProtocolApi.as_view(), name='modelapply'),  # 单个设备模板应用保存
    url(r'^devicemanage/devicededug/(?P<device_id>\d+)$', views.DeviceDebugView.as_view(), name='devicededug'),  # 单个设备调试页面
    url(r'^devicemanage/devicedataforward/(?P<device_id>\d+)$', views.DeviceDataView.as_view(), name='devicedataforward'),  # 单个设备数据转发页面
    url(r'^delete/', views.DeviceDeleteApi.as_view(), name='devicedelete'),  # 单个设备删除
    url(r'^update$', views.DeviceUpdateApi.as_view(), name='deviceupdate'),  # 单个设备启用禁用更新
    url(r'^transmit/update$', views.TransmitUpdateApi.as_view(), name='transmitupdate'),  # 数据转发更新
    url(r'^transmit/delete$', views.TransmitDeleteApi.as_view(), name='transmitdelete'),  # 数据转发删除
    url(r'^transmit/count$', views.TransmitCountApi.as_view(), name='transmitcount'),  # 数据转发计数
    url(r'^transmit/modify$', views.TransmitModifyApi.as_view(), name='transmitmodify'),  # 数据转发计数
    url(r'^modify/', views.DeviceModifyApi.as_view(), name='devicemodify'),  # 单个设备信息修改页面

]

apps/user/urls.py
from django.conf.urls import url
# from user import views
from apps.user import views

# app_name = 'user'
app_name = 'apps.user'
urlpatterns = [
    url(r'register/$', views.RegisterView.as_view(), name='register'),  # 注册页面
    url(r'^active/(?P<token>.*)$', views.ActiveView.as_view(), name='active'),  # 用户激活
]

edgebox_web/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.user.views import LoginView
from apps.shebei.views import DeviceView
from django.contrib.auth.decorators import login_required

name="main"
urlpatterns = [

    path('apidata/',include('apps.apidata.urls', namespace='apidata')),
    path('admin/', admin.site.urls),
    # path('search/', include('haystack.urls')),  # 全文检索框架
    path('user/', include('apps.user.urls', namespace='user')),  # 用户登录注册模块
    path('wangguang/', include('apps.wangguang.urls', namespace='wangguang')),  # 网关管理模块
    path('m5/', include('apps.m5.urls', namespace='m5')),  # m5扩展模块
    path('shebei/', include('apps.shebei.urls', namespace='shebei')),  # 设备管理模块
    path('yuancheng/', include('apps.yuancheng.urls', namespace='yuancheng')),  # 远程管理模块
    path('loginfo/', include('apps.loginfo.urls', namespace='loginfo')),  # 日志管理模块
    path('qudong/', include('apps.qudong.urls', namespace='qudong')),  # 驱动管理模块
    path('login/', LoginView.as_view(), name="login"),  # 登录页面
    path('accounts/login/', LoginView.as_view(), name="login"),  # 登录页面
    path('', LoginView.as_view()),  # 登录页面
    path('index/', login_required(DeviceView.as_view()), name="index"),  # 主页(登录验证)
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
	<head>
		<meta charset="UTF-8">
		<title>网关信息</title>
		<link rel="stylesheet" href="{% static 'css/Main.css' %}" />
		<link rel="stylesheet" href="{% static 'css/pop.css' %}" />
		<link rel="stylesheet" href="{% static 'css/iframe.css'%}" />
		<script type="text/javascript" src="{% static 'js/jquery.js' %}" ></script>
	</head>
	<body>
			<div id="leftMenu">
				<div id="topImage">
					<img id="u61_img" src="{% static 'img/gateway/u61.jpg' %}">
				</div>
				<div id="defaultMenu">
					<div id="box" class="box" onclick="clickDiv(className,0)" onmouseover="over(className,0)" onmouseout="out(className,0)">
						<a href="javascript:void(0)">
						<div id="u154"><img id="u154_img" class="list_img" src="{% static 'img/gateway/gateway_manage/0.png' %} " /></div>
						<div id="box_1" class="menuList">网关管理</div></a>
					</div>
					<div class="box" onclick="clickDiv(className,1)" onmouseover="over(className,1)" onmouseout="out(className,1)">
						<a href="javascript:void(0)">
						<div id="u85"><img id="u85_img" class="list_img" src="{% static 'img/gateway/gateway_manage/1.png' %} " /></div>
						<div id="box_2" class="menuList">子设备管理</div></a>
					</div>
					<div class="box" onclick="clickDiv(className,2)" onmouseover="over(className,2)" onmouseout="out(className,2)">
						<a href="javascript:void(0)">
						<div id="u68"><img id="u68_img" class="list_img" src="{% static 'img/gateway/gateway_manage/2.png' %} " /></div>
						<div id="box_3" class="menuList">远程管理及维护</div></a>
					</div>
					<div class="box" onclick="clickDiv(className,3)" onmouseover="over(className,3)" onmouseout="out(className,3)">
						<a href="javascript:void(0)">
						<div id="u105"><img id="u105_img" class="list_img" src="{% static 'img/gateway/gateway_manage/3.png' %}" /></div>
						<div id="box_4" class="menuList">日志事件</div></a>
					</div>
					<div class="box" onclick="clickDiv(className,4)" onmouseover="over(className,4)" onmouseout="out(className,4)">
						<a href="javascript:void(0)">
						<div id="u83"><img id="u83_img" class="list_img" src="{% static 'img/gateway/gateway_manage/4.png' %} " /></div>
						<div id="box_5" class="menuList">设备驱动库</div></a>
					</div>
					<div class="box" onclick="clickDiv(className,5)" onmouseover="over(className,5)" onmouseout="out(className,5)">
						<a href="javascript:void(0)">
						<div id="u83"><img id="u83_img" class="list_img" src="{% static 'img/gateway/gateway_manage/5.png' %} " /></div>
						<div id="box_6" class="menuList">M5对接模块</div></a>
					</div>
					<div id="u91"><img id="u91_img" src="{% static 'img/gateway/u91.png' %} " /></div>
				</div>
			</div>
			<div>
				<div id="dashboard"><span>DashBoard</span></div>
				<div id="top_u40"><img id="u40_img" src="{% static 'img/gateway/u40.png' %} " /></div>
				<div id="sign_out_div" class="div_cursor font_white"><span id="sign_out">退出</span></div>
				<div id="top_u302"><img id="u302_img" src="{% static 'img/gateway/u302.png' %} " /><span id="user_span" class="font_white">{{ user.username }} </span></div>
				<div id="u157" class="div_cursor" onmouseover="display_edition(true)" onmouseout="display_edition(false)"><img id="u157_img" src="{% static 'img/gateway/u157.png' %} " /></div>
			</div>
			
			<div id="edition">
				<span>当前版本V1.0,发布时间2019/07/11</span>
			</div>
			<iframe id="inteface_iframe" name="inteface_iframe" src="{% url 'shebei:devicelist'%}"></iframe>

			<!--<iframe id="inteface_iframe" name="inteface_iframe" src="gateway_manage/Gateway_main.html"></iframe>-->
			<!--<iframe id="inteface_iframe" name="inteface_iframe" src="Remote_Manage/Remote_Manage_Main.html"></iframe>-->

			
			
			
			
		<script type="text/javascript" src="{% static 'js/Main.js' %} " ></script>
		<script type="text/javascript" src="{% static 'js/pop.js' %} " ></script>
	</body>
</html>

templates/login.html
{% load staticfiles %}

<html>
<head>
	<meta charset="utf-8">
	<title>Edge Box 边缘层智能网关</title>
	<link rel="stylesheet" href="{% static 'css/auth.css' %}">
</head>

<body>
	<div class="login login-blue">
		<div class="login-wrapper">
			<div class="login-box">
				<div class="login-box-inner">
					<form method="post">
						{% csrf_token %}
						<p>Edge Box 边缘层智能网关</p>
						<div class="login-group">
							<label>用户名
							<input type="username" autocomplete="username" name="username" class="login-input">
							</label>
						</div>
						<div class="login-group password-group">
							<label>密 码
							<input type="password" name="password" autocomplete="current-password" class="login-input">
							</label>
						</div>
						{{ errmsg }}
						<button type="submit" class="login-btn">登 入</button>

						<div class="text-foot">
							还没有账号? <a href="{% url 'user:register'%}">注册</a>
						</div>
					</form>
				</div>		
			</div>
		</div>		

	</div>


</body>
</html>

templates/register.html
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>Edge Box 边缘层智能网关</title>
	<link rel="stylesheet" href="{% static 'css/auth.css' %}">
</head>

<body>
	<div class="login login-blue">
		<div class="login-wrapper">
			<div class="login-box">
				<div class="login-box-inner">
					<form method="post">
						{% csrf_token %}
						<p>用户注册页面</p>
						<div class="login-group">
							<label>用户名*</label>
							<input type="username" autocomplete="username" name="username" class="login-input">
						</div>
						<div class="login-group password-group">
							<label>邮 箱*(内部邮箱)</label>
							<input name="email" class="login-input" >
						</div>
						<div class="login-group password-group">
							<label>密 码*</label>
							<input type="password" name="password" autocomplete="current-password" class="login-input">
						</div>
						{{ errmsg }}
						<button type="submit" class="login-btn">注 册 激 活</button>
						<div class="text-foot">
							已经有账号? <a href="{% url 'login'%}">登录</a>
						</div>
					</form>
				</div>		
			</div>
		</div>		

	</div>


</body>
</html>